<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.project.referral</groupId>
        <artifactId>job-referral-system</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>job-portal-services</artifactId>
    <packaging>pom</packaging>
    <name>job-portal-services</name>
    <description>Business Services Modules</description>

    <modules>
        <module>job-portal-user-service</module>
        <module>job-portal-company-service</module>
        <module>job-portal-job-service</module>
        <module>job-portal-application-service</module>
        <module>job-portal-resume-service</module>
        <module>job-portal-preference-service</module>
        <module>job-portal-ai-service</module>
    </modules>

</project>
