networks:
  job-portal-net:
    driver: bridge
volumes:
  userdb_data:
  companydb_data:
  jobdb_data:
  applicationdb_data:
  paymentdb_data:
  subscriptiondb_data:
  preferencedb_data:
  resumedb_data:
services:
#
#  # ============================================================
#  # DATABASES (One MySQL container per microservice)
#  # ============================================================
#
  userdb:
    image: mysql:8.4
    container_name: job-portal-userdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job-portal-user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - userdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  companydb:
    image: mysql:8.4
    container_name: job-portal-companydb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_company
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - companydb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  jobdb:
    image: mysql:8.4
    container_name: job-portal-jobdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_job
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - jobdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  applicationdb:
    image: mysql:8.4
    container_name: job-portal-applicationdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_application
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - applicationdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  paymentdb:
    image: mysql:8.4
    container_name: job-portal-paymentdb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_payment
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - paymentdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  subscriptiondb:
    image: mysql:8.4
    container_name: job-portal-subscriptiondb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_subscription
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - subscriptiondb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  preferencedb:
    image: mysql:8.4
    container_name: job-portal-preferencedb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3313:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_preference
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - preferencedb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net

  resumedb:
    image: mysql:8.4
    container_name: job-portal-resumedb
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "3314:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: job_portal_resume
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - resumedb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - job-portal-net


#  # ============================================================
#  # SPRING CLOUD
#  # ============================================================
#
  discovery:
    image: ritesh8554/job-portal-service-registry:latest
    container_name: job-portal-service-registry
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
    networks:
      - job-portal-net

  config-server:
    image: ritesh8554/job-portal-config-server:latest
    container_name: job-portal-config-server
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8888:8888"
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
    networks:
      - job-portal-net

  gateway:
    image: ritesh8554/job-portal-api-gateway:latest
    container_name: job-portal-api-gateway
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "5000:5000"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net

  user-service:
    image: ritesh8554/job-portal-user-service:latest
    container_name: job-portal-user-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8083:8083"
    depends_on:
      userdb:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      DB_URL: jdbc:mysql://userdb:3306/job-portal-user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: jobportal
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    networks:
      - job-portal-net