networks:
  job-portal-net:
    driver: bridge
#volumes:
#  userdb_data:
#  companydb_data:
#  jobdb_data:
#  applicationdb_data:
#  paymentdb_data:
#  subscriptiondb_data:
#  preferencedb_data:
#  resumedb_data:
services:
#
#  # ============================================================
#  # DATABASES (One MySQL container per microservice)
#  # ============================================================
#
#  userdb:
#    image: mysql:8.4
#    container_name: job-portal-userdb
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: job-portal-user-service
#      MYSQL_USER: root
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - userdb_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - job-portal-net
#
#  companydb:
#    image: mysql:8.4
#    container_name: job-portal-companydb
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: job_portal_company
#      MYSQL_USER: jobportal
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - companydb_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - job-portal-net
#
#  jobdb:
#    image: mysql:8.4
#    container_name: job-portal-jobdb
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "3309:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: job_portal_job
#      MYSQL_USER: jobportal
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - jobdb_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - job-portal-net
#
#  applicationdb:
#    image: mysql:8.4
#    container_name: job-portal-applicationdb
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "3310:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: job_portal_application
#      MYSQL_USER: jobportal
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - applicationdb_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - job-portal-net
#
#  preferencedb:
#    image: mysql:8.4
#    container_name: job-portal-preferencedb
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "3313:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: job_portal_preference
#      MYSQL_USER: jobportal
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - preferencedb_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - job-portal-net
#
#  resumedb:
#    image: mysql:8.4
#    container_name: job-portal-resumedb
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "3314:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: job_portal_resume
#      MYSQL_USER: jobportal
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - resumedb_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - job-portal-net


#  # ============================================================
#  # SPRING CLOUD
#  # ============================================================
#
  discovery:
    image: ritesh8554/job-portal-service-registry:latest
    container_name: job-portal-service-registry
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 30s
    networks:
      - job-portal-net

  config-server:
    image: ritesh8554/job-portal-config-server:latest
    container_name: job-portal-config-server
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8888:8888"
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 30s
    networks:
      - job-portal-net

  gateway:
    image: ritesh8554/job-portal-api-gateway:latest
    container_name: job-portal-api-gateway
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "5000:5000"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:5000/actuator/health || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 30s
    networks:
      - job-portal-net

  user-service:
    image: ritesh8554/job-portal-user-service:latest
    container_name: job-portal-user-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      DB_URL: jdbc:mysql://db-context-contextai.e.aivencloud.com:17475/jobx?sslMode=REQUIRED
      DB_USERNAME: avnadmin
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8083/actuator/health || exit 1" ]
      start_period: 30s
    networks:
      - job-portal-net

  company-service:
      image: ritesh8554/job-portal-company-service:latest
      container_name: job-portal-company-service
      mem_limit: 512m
      mem_reservation: 256m
      cpus: 0.5
      ports:
        - "8086:8086"
      depends_on:
        config-server:
          condition: service_healthy
      environment:
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
        DB_URL: jdbc:mysql://db-context-contextai.e.aivencloud.com:17475/jobx?sslMode=REQUIRED
        DB_USERNAME: avnadmin
        DB_PASSWORD: ${DB_PASSWORD}
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
        EUREKA_URL: http://discovery:8761/eureka
        SERVER_PORT: 8086
      healthcheck:
        test: [ "CMD-SHELL", "wget -qO- http://localhost:8086/actuator/health || exit 1" ]
        start_period: 30s
      networks:
        - job-portal-net


  job-service:
    image: ritesh8554/job-portal-job-service:latest
    container_name: job-portal-job-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8085:8085"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      DB_URL: jdbc:mysql://db-context-contextai.e.aivencloud.com:17475/jobx?sslMode=REQUIRED
      DB_USERNAME: avnadmin
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      EUREKA_URL: http://discovery:8761/eureka
      SERVER_PORT: 8085
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8085/actuator/health || exit 1" ]
      start_period: 30s
    networks:
      - job-portal-net

  application-service:
    image: ritesh8554/job-portal-application-service:latest
    container_name: job-portal-application-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8084:8084"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      DB_URL: jdbc:mysql://db-context-contextai.e.aivencloud.com:17475/jobx?sslMode=REQUIRED
      DB_USERNAME: avnadmin
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      EUREKA_URL: http://discovery:8761/eureka
      SERVER_PORT: 8084
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8084/actuator/health || exit 1" ]
      start_period: 30s
    networks:
      - job-portal-net

#  notification-service:
#    image: ritesh8554/job-portal-notification-service:latest
#    container_name: job-portal-notification-service
#    mem_limit: 512m
#    mem_reservation: 256m
#    cpus: 0.5
#    ports:
#      - "8090:8090"
#    depends_on:
#      kafka:
#        condition: service_healthy
#      config-server:
#        condition: service_healthy
#    environment:
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      DB_URL: jdbc:mysql://notificationdb:3306/job-portal-notification?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      DB_USERNAME: jobportal
#      DB_PASSWORD: ${DB_PASSWORD}
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
#      EUREKA_URL: http://discovery:8761/eureka
#      SERVER_PORT: 8090
#      MAIL_HOST: smtp.gmail.com
#      MAIL_PORT: 587
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#    networks:
#      - job-portal-net
  preference-service:
    image: ritesh8554/job-portal-preference-service:latest
    container_name: job-portal-preference-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8087:8087"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      DB_URL: jdbc:mysql://db-context-contextai.e.aivencloud.com:17475/jobx?sslMode=REQUIRED
      DB_USERNAME: avnadmin
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      EUREKA_URL: http://discovery:8761/eureka
      SERVER_PORT: 8087
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8087/actuator/health || exit 1" ]
      start_period: 30s
    networks:
      - job-portal-net

  resume-service:
    image: ritesh8554/job-portal-resume-service:latest
    container_name: job-portal-resume-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8088:8088"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      DB_URL: jdbc:mysql://db-context-contextai.e.aivencloud.com:17475/jobx?sslMode=REQUIRED
      DB_USERNAME: avnadmin
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      EUREKA_URL: http://discovery:8761/eureka
      SERVER_PORT: 8088
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8088/actuator/health || exit 1" ]
      start_period: 30s
    networks:
      - job-portal-net
  ai-service:
    image: ritesh8554/job-portal-ai-service:latest
    container_name: job-portal-ai-service
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8089:8089"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
      EUREKA_URL: http://discovery:8761/eureka
      SERVER_PORT: 8089
    networks:
      - job-portal-net


