services:

  backend:

    image: 008714537729.dkr.ecr.ap-south-1.amazonaws.com/jobx-backend:1.0

    container_name: jobx-backend

    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env.production

    environment:

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      SPRING_SECURITY_USERNAME: ${SPRING_SECURITY_USERNAME}
      SPRING_SECURITY_PASSWORD: ${SPRING_SECURITY_PASSWORD}

      AWS_REGION: ${AWS_REGION}
      AWS_SES_SENDER_EMAIL: ${AWS_SES_SENDER_EMAIL}

    networks:
      - jobx-network

networks:

  jobx-network:
    driver: bridge