####################################
# Database
####################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

####################################
# Redis (Docker)
####################################

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.ssl.enabled=false

####################################
# Logging
####################################

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

####################################
# Security
####################################

spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

####################################
# AWS
####################################

aws.ses.sender-email=${AWS_SES_SENDER_EMAIL}