####################################
# Database
####################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

####################################
# Redis
####################################

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

####################################
# Logging
####################################

logging.level.root=INFO

####################################
# Security
####################################

spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

####################################
# AWS
####################################

aws.ses.sender-email=${AWS_SES_SENDER_EMAIL}