spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Common Redis Settings
spring.data.redis.port=6379

# Common AWS
aws.region=ap-south-1

#hikari specification
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000


####################################################
# Spring Boot Actuator
####################################################

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

####################################################
# Application Information
####################################################

info.app.name=JobX Backend
info.app.description=AI Powered Recruitment Platform
info.app.version=1.0.0
info.app.environment=${SPRING_PROFILES_ACTIVE}


management.endpoint.health.probes.enabled=true

management.health.livenessstate.enabled=true

management.health.readinessstate.enabled=true

management.health.redis.enabled=true

management.health.db.enabled=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] [%thread] %logger{36} - %msg%n